### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by psibi** [fakedata-haskell/fakedata-quickcheck#1]
Would be nice to have CI integration via github actions

**Comment by jappeace** [comment]
I've done this with a nix-build for now. Seems to work: https://github.com/fakedata-haskell/fakedata-quickcheck/pull/3

I'll wait for that to finish before closing this.

**Comment by jappeace** [comment]
I think we have this :ok_hand:

**Comment by psibi** [comment]
@jappeace Do you think we can have against different stackage resolvers ?

**Comment by jappeace** [comment]
You mean different ghc versions? I'm not sure how to do any stack things, I could run it in the shell. Or maybe you have a config that would do this somehwere?

**Comment by psibi** [comment]
@jappeace 

> You mean different ghc versions?

Kind of. But against different lts resolvers. You can take the configuration from the `fakedata` package. Or optionally I could create an MR this weekend.

**Comment by jappeace** [comment]
Please make an MR over the weekend if you can, I've been reading that the maintainer agreement and approaching stack tools would be best for that, but just testing various ghc versions also seems good so I added some support for that as well. Thanks for your help btw :+1:

**Comment by psibi** [comment]
Finally, this has bee done.
