### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by psibi** [fakedata-haskell/fakedata-quickcheck#2]
Would be nice to have it added to Stackage package set

**Comment by jappeace** [comment]
How do I do this? Will it work with a hackage release?

**Comment by psibi** [comment]
@jappeace There are some docs here: https://github.com/commercialhaskell/stackage#add-your-package

Let me know if you have questions.

**Comment by psibi** [comment]
Fixed via https://github.com/commercialhaskell/stackage/pull/6082
